#!/bin/bash

#initialize
package=''
args=("$@")

download=false
delete=false
install=false
force=false

#process arguments
for (( i=0; i<${#args[@]}; i++)); do
	arg=${args[i]}
	if [[ ${arg:0:1} == '-' ]]; then
		#set install and get package name
		if [[ $arg == *S* ]]; then
			install=true
			download=true
			delete=true
			package=${args[i+1]}
		fi

		#install only
		if [[ $arg == *I* ]]; then
			install=true
			package=${args[i+1]}
		fi

		if [[ $arg == *f* ]]; then
			force=true
		fi

		if [[ $arg == *c* ]]; then
			delete=true
		fi

		#show help
		if [[ $arg == *h* ]]; then
			echo 'aur help'
			echo
			echo 'options:'
			echo '    S : basic install'
			echo '    I : install only'
			echo '    e : edit package'
			echo '        do not install or delete'
			echo '        used with S'
			echo '    c : cleanup'
			echo '        default with S'
			echo '        not default with I'
			echo '    d : keep dirty'
			echo '        do not cleanup'
			echo '        used with S'
			echo '    f : force install'
			echo '        used with S or I'
			echo '    h : display help'
			echo
			echo 'usage examples:'
			echo '    aur -S [package]   : install'
			echo '    aur -Se [package]  : download to edit in ~/.aur/'
			echo '    aur -Ic [package]  : install from and clear ~/.aur/'
			echo '    aur -c             : clear ~/.aur/'
			echo '    aur -Sd [package]  : install without clearing'
			echo '                         avoids downloading again if'
			echo '                         occurs'
			echo '    aur -Sf [package]  : install forcibly'
			echo
		fi

		#edit before install
		if [[ $arg == *e* ]]; then
			delete=false
			install=false
		fi

		#keep dirty
		if [[ $arg == *d* ]]; then
			delete=false
		fi
	fi
done

#make aur directory if it doesn't exist
if [[ ! -e ~/.aur ]]; then
	mkdir ~/.aur
fi

#change working directory to aur directory
cd ~/.aur

#download
if [[ $download == true ]]; then
	wget --no-check-certificate https://aur.archlinux.org/packages/${package:0:2}/${package}/${package}.tar.gz

	#unzip
	tar -xzf ${package}.tar.gz
fi

if [[ $install == true ]]; then
	#enter dir
	cd ${package}

	#open README
	less $(find . -name 'READ*')

	#package
	makepkg -s
	
	if [[ $force == true ]]; then
		#force install
		su -c "pacman -U --force ${package}*.pkg.tar.xz"
	else
		#install
		su -c "pacman -U ${package}*.pkg.tar.xz"
	fi
fi

if [[ $delete == true ]]; then
	#clean up
	cd ~
	rm -rf ~/.aur/${package}*
fi
